version: 2.1
jobs:
  setup_and_test:
    macos:
      xcode: 11.3.0
    # docker:
    #   - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Get CMake and miniconda
          command: |
            # sudo apt install cmake
            brew install cmake libomp
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
            # curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
            bash miniconda.sh -b -p ./miniconda
            source "./miniconda/etc/profile.d/conda.sh"
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda create -y -n test_env python=3.8
            conda activate test_env
            conda install --yes --file requirements.txt
      - run:
          name: Get libraries and build
          command: |
            cd cpp
            git clone https://github.com/pybind/pybind11.git
            curl -O https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
            git clone https://github.com/autodiff/autodiff
            mv autodiff autodiff_tmp
            mv autodiff_tmp/autodiff .
            rm -rf autodiff_tmp
            tar -xf eigen-3.3.9.tar.gz
            rm eigen-3.3.9.tar.gz
            mv eigen-3.3.9 eigen

            cmake .
            make
            cd ../
            # source setup.sh

workflows:
  Main:
    jobs:
      - setup_and_test